name: huntersmark
version: 1.0.0
author: William Wofford
main: us.williamwofford.huntersmark.HuntersMark
api-version: 1.16
permissions:
  huntersmark.basic:
    description: Anyone can use these commands.
    default: true
commands:
  listhunters:
    description: Lists all Hunters. Hunters that are offline will appear in grey.
    usage: /listhunters
    permission: huntersmark.basic
    permission-message: Insufficient permissions to execute command.
  hunter:
    description: Sets or unsets using player as a Hunter.
    usage: /hunter
    permission: huntersmark.basic
    permission-message: Insufficient permissions to execute command.
  target:
    description: Sets or unsets a specific player to target.
    usage: /target <player>
    permission: huntersmark.basic
    permission-message: Insufficient permissions to execute command.