name: huntersmark
version: 1.0.0
author: William Wofford
main: us.williamwofford.huntersmark.HuntersMark
api-version: 1.16
permissions:
  huntersmark.basic:
    description: Anyone can use these commands.
    default: true
  huntersmark.hunter:
    description: Only Hunter Players can use these commands.
    default: not-op
commands:
  listhunters:
    description: Lists all Hunters. Hunters that are offline will appear in grey.
    usage: /listhunters
    permission: huntersmark.basic
  hunter:
    description: Sets or unsets a player as a Hunter.
    usage: /hunter [player]
    permission: huntersmark.basic
  target:
    description: Sets or unsets a specific player to target.
    usage: /target <player>
    permission: huntersmark.hunter